actor_critic:
  actor:
    max_tokens: 1000
    model: gpt-4o
    temperature: 0.8
  critic:
    geometric_weight: 0.6
    semantic_weight: 0.4
constraint_generator:
  max_tokens: 4096
  model: gpt-4.1
  temperature: 0.0
device: cuda
env:
  bounds_max: &id001
  - 0.495789
  - 0.46111599999999997
  - 0.5627120000000001
  bounds_min: &id002
  - -0.068104
  - -0.276093
  -  0.00
  camera:
    0:
      name: cam_0
      orientation:
      - 0.055
      - 0.0544
      - 0.701
      - 0.709
      position:
      - -0.1655
      - 0.0167
      - 1.3664
      resolution: 480
    1:
      name: cam_1
      orientation:
      - 0.3212
      - 0.4682
      - 0.6788
      - 0.4656
      position:
      - 0.6137
      - 0.4764
      - 1.4565
      resolution: 480
  interpolate_pos_step_size: 0.05
  interpolate_rot_step_size: 0.34
  og_sim:
    action_frequency: 15
    physics_frequency: 100
  robot:
    robot_config:
      action_modalities: continuous
      action_normalize: false
      controller_config:
        arm_0:
          damping_ratio: 0.6
          kp: 250
          kp_limits:
          - 50
          - 400
          name: OperationalSpaceController
        base:
          name: DifferentialDriveController
        camera:
          name: JointController
        gripper_0:
          command_input_limits:
          - 0.0
          - 1.0
          mode: smooth
          name: MultiFingerGripperController
      grasping_mode: assisted
      name: Fetch
      obs_modalities:
      - rgb
      - depth
      position:
      - -0.8
      - 0.0
      - 0.0
      type: Fetch
  scene:
    name: Rs_int
    scene_model: Rs_int
    type: InteractiveTraversableScene
  video_cache_size: 2000
keypoint_proposer:
  bounds_max: *id001
  bounds_min: *id002
  device: cuda
  max_mask_ratio: 0.5
  min_dist_bt_keypoints: 0.04
  num_candidates_per_mask: 3
  seed: 0
main:
  action_steps_per_iter: 5
  bounds_max: *id001
  bounds_min: *id002
  constraint_tolerance: 0.1
  grasp_depth: 0.1
  interpolate_pos_step_size: 0.05
  interpolate_rot_step_size: 0.34
  sdf_voxel_size: 0.01
  seed: 0
  vlm_camera: 0
path_solver:
  bounds_max: *id001
  bounds_min: *id002
  constraint_tolerance: 0.0001
  max_collision_points: 60
  minimizer_options:
    maxiter: 200
  opt_interpolate_pos_step_size: 0.02
  opt_interpolate_rot_step_size: 0.1
  opt_pos_step_size: 0.2
  opt_rot_step_size: 0.78
  sampling_maxfun: 5000
perception:
  cameras:
    depth_pro:
      fps: 60
      resolution:
      - 640
      - 480
    zed2:
      fps: 30
      resolution:
      - 1280
      - 720
  fusion:
    registration_method: icp
    voxel_size: 0.01
seed: 0
subgoal_solver:
  bounds_max: *id001
  bounds_min: *id002
  constraint_tolerance: 0.0001
  max_collision_points: 60
  minimizer_options:
    maxiter: 200
  sampling_maxfun: 5000
visualizer:
  bounds_max: *id001
  bounds_min: *id002
